config/routes.rb
LookingDeveloper::Application.routes.draw do
  resources :repositories do
    collection do
      get 'import'
    end
  end

  root :to => 'users#index'

  resources :types do
    collection do
      get 'rank'
    end
  end

  resources :looking_types do
    collection do
      get 'rank'
    end
  end

  resources :commit_logs

  resources :users do
    collection do
      get 'login'
    end
    resources :looking_types
    resources :commit_logs
  end

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  validates_presence_of :url
  validates_uniqueness_of :url
  
  def import
    User.import_repository_data(self)
    CommitLog.import_repository_data(self)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_filter :authenticate, :except => ["rank"]
  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all

    respond_to do |format|
      if smartphone?
        format.html { render :template => 'repositories/index_smp' }
      else
        format.html # index.html.erb
        format.json { render :json => @repositories }
      end
    end
  end

  def import
    @repository = Repository.find_by_id(params[:id])
    unless @repository.nil?
      @repository.import
    end
    redirect_to @repository, :notice => 'Repository datawas successfully imported.'
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.json
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, :notice => 'Repository was successfully created.' }
        format.json { render :json => @repository, :status => :created, :location => @repository }
      else
        format.html { render :action => "new" }
        format.json { render :json => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.json
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to @repository, :notice => 'Repository was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/_list_smp.html.erb
<div data-role="content">
  <ul data-role="listview">
    <% @repositories.each do |repo| %>
    <li><%= repo.url %>
    <a href="/repositories/import?id=<%= repo.id %>">
    <span class="ui-li-count">import</span>
    </a>
    </li>
    <% end %>
  </ul>
</div>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repositories.each do |repository| %>
  <tr>
    <td><%= repository.url %></td>
    <td><%= link_to 'Show', repository %></td>
    <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
    <td><%= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/index_smp.html.erb
<div data-role="header" data-position="inline" data-nobackbtn="true">
  <%= link_to 'Back', users_path , {"class" => "ui-btn-left", "data-icon" => "back"} %>
  <h1>Listing Repository</h1>
</div>
<%= render 'list_smp' %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @repository.url %>
</p>


<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>