config/routes.rb
LookingDeveloper::Application.routes.draw do
  resources :repositories do
    collection do
      get 'import'
    end
  end

  root :to => 'users#index'

  resources :types do
    collection do
      get 'rank'
    end
  end

  resources :looking_types do
    collection do
      get 'rank'
    end
  end

  resources :commit_logs

  resources :users do
    collection do
      get 'login'
    end
    resources :looking_types
    resources :commit_logs
  end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_filter :authenticate, :except => ["rank","show"]
  # GET /types
  # GET /types.json
  def index
    @types = Type.all.sort{|a,b| a.name <=> b.name }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @types }
    end
  end

  def rank
    @types = Type.rank
    respond_to do |format|
      if smartphone?
        format.html { render :template => "types/rank_smp"}
      else
        format.html # rank.html.erb
        format.json { render :json => @types }
      end
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      if smartphone?
        format.html { render :template => "types/show_smp"}
      else
        format.html # show.html.erb
        format.json { render :json => @type }
      end
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, :notice => 'Type was successfully created.' }
        format.json { render :json => @type, :status => :created, :location => @type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, :notice => 'Type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pattern %><br />
    <%= f.text_field :pattern %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pattern</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.name %></td>
    <td><%= type.pattern %></td>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/rank.html.erb
<h1>Ranking types</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Count</th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type[:name] %></td>
    <td><%= type[:count] %></td>
  </tr>
<% end %>
</table>

<br />

app/views/types/rank_smp.html.erb
<div data-role="header" data-position="inline" data-nobackbtn="true">
  <%= link_to 'Back', users_path , {"class" => "ui-btn-left", "data-icon" => "back"} %>
  <h1>Ranking types</h1>
</div>

<div data-role="content">
  <ul data-role="listview">
    <% @types.each do |type| %>
    <li><a href="/types/<%= type[:id] %>"><%= type[:name]%><span class="ui-li-count"><%= type[:count] %></span></a></li>
    <% end %>
  </ul>
</div>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Pattern:</b>
  <%= @type.pattern %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/types/show_smp.html.erb
<p id="notice"><%= notice %></p>
<div data-role="header" data-position="inline" data-nobackbtn="true">
  <h1><%= @type.name %></h1>
</div>

<div data-role="content">
  <ul data-role="listview">
    <% @type.rank.each_with_index do |rank,index| %>
    <li><b><%= (index+1) %>.</b> &nbsp;<a href="/users/<%= rank[:id] %>"><%= rank[:name] %><span class="ui-li-count"><%= rank[:count] %></span></a></li>
    <% end %>
  </ul>
</div>