config/routes.rb
LookingDeveloper::Application.routes.draw do
  resources :repositories do
    collection do
      get 'import'
    end
  end

  root :to => 'users#index'

  resources :types do
    collection do
      get 'rank'
    end
  end

  resources :looking_types do
    collection do
      get 'rank'
    end
  end

  resources :commit_logs

  resources :users do
    collection do
      get 'login'
    end
    resources :looking_types
    resources :commit_logs
  end

end

app/models/commit_log.rb
class CommitLog < ActiveRecord::Base
  validates_presence_of :commit_at,:user_id
  validates_uniqueness_of :commit_at, :scope => [:user_id,:type_id]
  belongs_to :user
  belongs_to :type

  def self.import_repository_data(repo)
    users = User.all
    repos = Repository.all
    types = Type.all
    types_count = {}
    if Rails.env == "production"
      tmp_path = "#{Rails.root}/public"
    else
      tmp_path = "#{Rails.root}/tmp"
    end
    repo_path = "#{tmp_path}/repo"
    if Dir.exist?(repo_path)
      `rm -rf #{repo_path}`
    end
    
    `git clone #{repo.url} #{repo_path}`
    users.each do |user|
      types.each do |type|
        types_count[type.name] = 0
      end
      commit_at = ""
      `cd #{repo_path} && git log --author #{user.name} --name-only > #{tmp_path}/#{user.name}_git_log.txt`
      open("#{tmp_path}/#{user.name}_git_log.txt").each do |line|
        if line.include?("Date")
          commit_at = line.gsub("Date:   ","")
        end
        types.each do |type|
          if line.include?(type.pattern)
            types_count[type.name] += 1
          end
        end
      end
      types.each do |type|
        if types_count[type.name] > 0
          CommitLog.create(:commit_at => commit_at,:user_id => user.id, :type_id => type.id,:count => types_count[type.name])
        end
      end
      `rm "#{tmp_path}/#{user.name}_git_log.txt"`
    end
    `rm -rf #{repo_path}`
  end
end

app/controllers/commit_logs_controller.rb
class CommitLogsController < ApplicationController
  before_filter :authenticate
  # GET /commit_logs
  # GET /commit_logs.json
  def index
    @commit_logs = CommitLog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @commit_logs }
    end
  end

  # GET /commit_logs/1
  # GET /commit_logs/1.json
  def show
    @commit_log = CommitLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @commit_log }
    end
  end

  # GET /commit_logs/new
  # GET /commit_logs/new.json
  def new
    @commit_log = CommitLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @commit_log }
    end
  end

  # GET /commit_logs/1/edit
  def edit
    @commit_log = CommitLog.find(params[:id])
  end

  # POST /commit_logs
  # POST /commit_logs.json
  def create
    @commit_log = CommitLog.new(params[:commit_log])

    respond_to do |format|
      if @commit_log.save
        format.html { redirect_to @commit_log, :notice => 'Commit log was successfully created.' }
        format.json { render :json => @commit_log, :status => :created, :location => @commit_log }
      else
        format.html { render :action => "new" }
        format.json { render :json => @commit_log.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commit_logs/1
  # PUT /commit_logs/1.json
  def update
    @commit_log = CommitLog.find(params[:id])

    respond_to do |format|
      if @commit_log.update_attributes(params[:commit_log])
        format.html { redirect_to @commit_log, :notice => 'Commit log was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @commit_log.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commit_logs/1
  # DELETE /commit_logs/1.json
  def destroy
    @commit_log = CommitLog.find(params[:id])
    @commit_log.destroy

    respond_to do |format|
      format.html { redirect_to commit_logs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/commit_logs_helper.rb
module CommitLogsHelper
end

app/views/commit_logs/_form.html.erb
<%= form_for(@commit_log) do |f| %>
  <% if @commit_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit_log.errors.count, "error") %> prohibited this commit_log from being saved:</h2>

      <ul>
      <% @commit_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commit_at %><br />
    <%= f.datetime_select :commit_at %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.number_field :type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commit_logs/edit.html.erb
<h1>Editing commit_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit_log %> |
<%= link_to 'Back', commit_logs_path %>

app/views/commit_logs/index.html.erb
<h1>Listing commit_logs</h1>

<table>
  <tr>
    <th>Commit at</th>
    <th>User</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commit_logs.each do |commit_log| %>
  <tr>
    <td><%= commit_log.commit_at %></td>
    <td><%= commit_log.user_id %></td>
    <td><%= commit_log.type_id %></td>
    <td><%= link_to 'Show', commit_log %></td>
    <td><%= link_to 'Edit', edit_commit_log_path(commit_log) %></td>
    <td><%= link_to 'Destroy', commit_log, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commit log', new_commit_log_path %>

app/views/commit_logs/new.html.erb
<h1>New commit_log</h1>

<%= render 'form' %>

<%= link_to 'Back', commit_logs_path %>

app/views/commit_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commit at:</b>
  <%= @commit_log.commit_at %>
</p>

<p>
  <b>User:</b>
  <%= @commit_log.user_id %>
</p>

<p>
  <b>Type:</b>
  <%= @commit_log.type_id %>
</p>


<%= link_to 'Edit', edit_commit_log_path(@commit_log) %> |
<%= link_to 'Back', commit_logs_path %>