config/routes.rb
LookingDeveloper::Application.routes.draw do
  resources :repositories do
    collection do
      get 'import'
    end
  end

  root :to => 'users#index'

  resources :types do
    collection do
      get 'rank'
    end
  end

  resources :looking_types do
    collection do
      get 'rank'
    end
  end

  resources :commit_logs

  resources :users do
    collection do
      get 'login'
    end
    resources :looking_types
    resources :commit_logs
  end

end

app/controllers/looking_types_controller.rb
class LookingTypesController < ApplicationController
  # GET /looking_types
  # GET /looking_types.json
  def index
    @looking_types = LookingType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @looking_types }
    end
  end

  def rank
    @looking_types = LookingType.rank
    respond_to do |format|
      if smartphone?
        format.html { render :template => "looking_types/rank_smp"}
      else
        format.html # rank.html.erb
        format.json { render :json => @looking_types }
      end
    end
  end

  # GET /looking_types/1
  # GET /looking_types/1.json
  def show
    @looking_type = LookingType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @looking_type }
    end
  end

  # GET /looking_types/new
  # GET /looking_types/new.json
  def new
    @looking_type = LookingType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @looking_type }
    end
  end

  # GET /looking_types/1/edit
  def edit
    @looking_type = LookingType.find(params[:id])
  end

  # POST /looking_types
  # POST /looking_types.json
  def create
    @looking_types = []
    params[:looking_types].each do |type|
      looking_type = {:type_id => type}
      looking_type.merge!(:user_id => params[:user_id])
      @looking_types << LookingType.new(looking_type)
    end

    respond_to do |format|
      if !@looking_types.empty? and @looking_types.all? { |looking_type| looking_type.save! }
#        format.html { redirect_to :controller => "users",:action => "show", :id => params[:user_id], :notice => 'Looking type was successfully created.' }
        format.html { redirect_to :controller => "users",:action => "show", :id => params[:user_id] }
        format.json { render :json => @looking_types, :status => :created, :location => @looking_types }
      else
        format.html { redirect_to :controller => "users",:action => "show", :id => params[:user_id] }
        format.json { render :json => @looking_types.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /looking_types/1
  # PUT /looking_types/1.json
  def update
    @looking_type = LookingType.find(params[:id])

    respond_to do |format|
      if @looking_type.update_attributes(params[:looking_type])
        format.html { redirect_to @looking_type, :notice => 'Looking type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @looking_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /looking_types/1
  # DELETE /looking_types/1.json
  def destroy
    @looking_type = LookingType.find(params[:id])
    @looking_type.destroy

    respond_to do |format|
      format.html { redirect_to looking_types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/looking_types_helper.rb
module LookingTypesHelper
end

app/views/looking_types/_form.html.erb
<%= form_for(@looking_type) do |f| %>
  <% if @looking_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@looking_type.errors.count, "error") %> prohibited this looking_type from being saved:</h2>

      <ul>
      <% @looking_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.number_field :type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/looking_types/edit.html.erb
<h1>Editing looking_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @looking_type %> |
<%= link_to 'Back', looking_types_path %>

app/views/looking_types/index.html.erb
<h1>Listing looking_types</h1>

<table>
  <tr>
    <th>User</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @looking_types.each do |looking_type| %>
  <tr>
    <td><%= looking_type.user_id %></td>
    <td><%= looking_type.type_id %></td>
    <td><%= link_to 'Show', looking_type %></td>
    <td><%= link_to 'Edit', edit_looking_type_path(looking_type) %></td>
    <td><%= link_to 'Destroy', looking_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Looking type', new_looking_type_path %>

app/views/looking_types/new.html.erb
<h1>New looking_type</h1>

<%= render 'form' %>

<%= link_to 'Back', looking_types_path %>

app/views/looking_types/rank.html.erb
<h1>Ranking looking_types</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Count</th>
  </tr>

<% @looking_types.each do |looking_type| %>
  <tr>
    <td><%= looking_type[:name] %></td>
    <td><%= looking_type[:count] %></td>
  </tr>
<% end %>
</table>

<br />

app/views/looking_types/rank_smp.html.erb
<div data-role="header" data-position="inline" data-nobackbtn="true">
  <%= link_to 'Back', users_path , {"class" => "ui-btn-left", "data-icon" => "back"} %>
  <h1>Ranking looking_types</h1>
</div>

<div data-role="content">
  <ul data-role="listview">
    <% @looking_types.each do |looking_type| %>
    <li><a href="/types/<%= looking_type[:id] %>"><%= looking_type[:name]%><span class="ui-li-count"><%= looking_type[:count] %></span></a></li>
    <% end %>
  </ul>
</div>

app/views/looking_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @looking_type.user_id %>
</p>

<p>
  <b>Type:</b>
  <%= @looking_type.type_id %>
</p>


<%= link_to 'Edit', edit_looking_type_path(@looking_type) %> |
<%= link_to 'Back', looking_types_path %>